"""Codex hook entrypoint for deterministic subagent routing.

Registered in the per-session private ``CODEX_HOME`` ``hooks.json``
generated by :mod:`omnigent.inner.codex_executor`. Three subcommands,
one per hook event:

- ``route-subagent`` (``PreToolUse``, matcher ``.*spawn_agent``) — asks
  the runner's ``route-subagent`` endpoint what model the spawn may use
  and rewrites / denies accordingly.
- ``session-canary`` (``SessionStart``) — touches a file in the bridge
  dir proving the generated hooks actually ran (an untrusted hook is
  silently skipped by codex, which would fail open invisibly).
- ``record-subagent`` (``SubagentStart``) — appends the ``agent_id`` /
  ``model`` codex actually started to an audit file for reconciliation.

Stdlib-only and short-lived: ``PreToolUse`` blocks the spawn.

Codex encrypts the spawn ``message`` field in hook payloads, so routing
signal comes from ``task_name`` plus session metadata only, and the
original ``tool_input`` is echoed back verbatim on a rewrite.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path
from typing import Any

from omnigent.inner.hook_scripts.subagent_router import (
    parse_hook_args,
    read_stdin_payload,
    run_route_subagent_main,
)

# Codex flattens MCP-ish tool names, so the spawn tool arrives as
# ``collaborationspawn_agent`` on 0.145.x. Both the hooks.json matcher
# and this check must stay suffix-based rather than a bare literal.
SPAWN_AGENT_TOOL_SUFFIX = "spawn_agent"
# Bridge-dir artifacts the canary / audit subcommands write.
CANARY_FILENAME = "subagent_routing_canary"
AUDIT_FILENAME = "subagent_spawn_audit.jsonl"
# Harness label sent to the endpoint when argv names none.
DEFAULT_HARNESS = "codex"

_LABEL = "omnigent codex router hook"
_MODULE = "omnigent.inner.hook_scripts.codex_router_hook"


def main(argv: list[str] | None = None) -> int:
    """
    Dispatch a codex router-hook subcommand.

    :param argv: Argv override excluding the program name. ``None`` reads
        :data:`sys.argv`.
    :returns: Process exit code. Always ``0`` — verdicts travel on stdout
        so a hook failure never wedges codex.
    """
    raw_argv = sys.argv[1:] if argv is None else argv
    command = raw_argv[0] if raw_argv else ""
    if command == "route-subagent":
        return run_route_subagent_main(
            raw_argv[1:],
            prog=_prog(command),
            harness=DEFAULT_HARNESS,
            label=_LABEL,
            **ROUTE_SEAMS,
        )
    if command == "session-canary":
        return _main_session_canary(raw_argv[1:])
    if command == "record-subagent":
        return _main_record_subagent(raw_argv[1:])
    print(f"{_LABEL}: unknown subcommand {command!r}", file=sys.stderr)
    return 0


def _prog(command: str) -> str:
    return f"python -m {_MODULE} {command}"


def is_spawn_agent_tool(tool_name: Any) -> bool:  # type: ignore[explicit-any]  # hook payloads are untrusted JSON
    """
    Report whether a hook payload names codex's subagent-spawn tool.

    :param tool_name: ``tool_name`` from the hook payload, e.g.
        ``"collaborationspawn_agent"``.
    :returns: ``True`` when the (flattened) name ends in
        ``spawn_agent``.
    """
    if not isinstance(tool_name, str):
        return False
    return tool_name.strip().lower().endswith(SPAWN_AGENT_TOOL_SUFFIX)


def with_system_message(
    output: dict[str, Any] | None,  # type: ignore[explicit-any]  # hook output JSON
) -> dict[str, Any] | None:  # type: ignore[explicit-any]  # hook output JSON
    """
    Add the routed-model notice codex's TUI surfaces to the user.

    A rewrite is otherwise invisible: codex reports no model change of its
    own, so the top-level ``systemMessage`` (alongside, not inside,
    ``hookSpecificOutput``) is the only place the decision shows up.

    :param output: Hook output from ``decision_to_hook_output``, or
        ``None`` for "no opinion".
    :returns: *output* with a ``systemMessage`` when it rewrote the spawn's
        model, otherwise *output* unchanged.
    """
    if not isinstance(output, dict):
        return output
    hook_output = output.get("hookSpecificOutput")
    if not isinstance(hook_output, dict) or hook_output.get("permissionDecision") != "allow":
        return output
    updated_input = hook_output.get("updatedInput")
    if not isinstance(updated_input, dict):
        return output
    model = updated_input.get("model")
    if not isinstance(model, str) or not model:
        return output
    return {**output, "systemMessage": f"Using Smart Routing. Routing to {model}."}


def _payload_model(payload: dict[str, Any]) -> str | None:  # type: ignore[explicit-any]  # hook payloads are untrusted JSON
    """
    Extract the parent session's model from a hook payload.

    :param payload: Codex hook payload.
    :returns: Model id, or ``None`` when the payload carries none.
    """
    model = payload.get("model")
    return model if isinstance(model, str) and model else None


#: How codex differs from the claude-native default: its own spawn-tool
#: name, its task-name keys, no prompt (codex encrypts the spawn message),
#: catalog ids injected verbatim, and the TUI routing notice.
ROUTE_SEAMS: dict[str, Any] = {  # type: ignore[explicit-any]  # route_pre_tool_use seams
    "tool_matcher": is_spawn_agent_tool,
    "task_keys": ("task_name", "agent_name"),
    "include_prompt": False,
    "parent_model_resolver": _payload_model,
    "model_translator_factory": None,
    "post_process": with_system_message,
}


def canary_path(bridge_dir: str | Path) -> Path:
    """
    Path of the ``SessionStart`` canary file.

    :param bridge_dir: Session bridge directory.
    :returns: Canary file path.
    """
    return Path(bridge_dir) / CANARY_FILENAME


def audit_path(bridge_dir: str | Path) -> Path:
    """
    Path of the ``SubagentStart`` audit file.

    :param bridge_dir: Session bridge directory.
    :returns: Audit file path (JSON lines).
    """
    return Path(bridge_dir) / AUDIT_FILENAME


def _main_session_canary(argv: list[str]) -> int:
    """
    Touch the canary file proving the generated hooks ran.

    :param argv: Argv after the ``session-canary`` subcommand.
    :returns: Process exit code. Always ``0``.
    """
    command = "session-canary"
    args = parse_hook_args(_prog(command), argv)
    if not args.bridge_dir:
        print(f"{_LABEL}: {command} needs --bridge-dir", file=sys.stderr)
        return 0
    path = canary_path(args.bridge_dir)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps({"session_id": args.session_id, "at": time.time()}),
            encoding="utf-8",
        )
    except OSError as exc:
        print(f"{_LABEL}: could not write canary: {exc}", file=sys.stderr)
    return 0


def _main_record_subagent(argv: list[str]) -> int:
    """
    Append one ``SubagentStart`` audit record.

    :param argv: Argv after the ``record-subagent`` subcommand.
    :returns: Process exit code. Always ``0``.
    """
    command = "record-subagent"
    args = parse_hook_args(_prog(command), argv)
    if not args.bridge_dir:
        print(f"{_LABEL}: {command} needs --bridge-dir", file=sys.stderr)
        return 0
    payload = read_stdin_payload(_LABEL)
    if payload is None:
        return 0
    record = {
        "agent_id": payload.get("agent_id") or payload.get("agentId"),
        "model": payload.get("model"),
        "task_name": payload.get("task_name"),
        "at": time.time(),
    }
    path = audit_path(args.bridge_dir)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(record) + "\n")
    except OSError as exc:
        print(f"{_LABEL}: could not write audit record: {exc}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
