"""Codex hook entrypoint for deterministic subagent routing.

Registered in the per-session private ``CODEX_HOME`` ``hooks.json``
generated by :mod:`omnigent.inner.codex_executor`. Three subcommands,
one per hook event:

- ``route-subagent`` (``PreToolUse``, matcher ``.*spawn_agent``) — asks
  the runner's ``route-subagent`` endpoint what model the spawn may use
  and rewrites / denies accordingly.
- ``session-canary`` (``SessionStart``) — touches a file in the bridge
  dir proving the generated hooks actually ran (an untrusted hook is
  silently skipped by codex, which would fail open invisibly).
- ``record-subagent`` (``SubagentStart``) — appends the ``agent_id`` /
  ``model`` codex actually started to an audit file for reconciliation.

Stdlib-only and short-lived: ``PreToolUse`` blocks the spawn.

Codex encrypts the spawn ``message`` field in hook payloads, so routing
signal comes from ``task_name`` plus session metadata only, and the
original ``tool_input`` is echoed back verbatim on a rewrite.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

from omnigent.inner.hook_scripts.subagent_router import (
    REQUEST_TIMEOUT_S,
    decision_to_hook_output,
    read_router_endpoint,
    request_decision,
    resolve_session_id,
)

# Codex flattens MCP-ish tool names, so the spawn tool arrives as
# ``collaborationspawn_agent`` on 0.145.x. Both the hooks.json matcher
# and this check must stay suffix-based rather than a bare literal.
SPAWN_AGENT_TOOL_SUFFIX = "spawn_agent"
# Bridge-dir artifacts the canary / audit subcommands write.
CANARY_FILENAME = "subagent_routing_canary"
AUDIT_FILENAME = "subagent_spawn_audit.jsonl"
# Harness label sent to the endpoint (§5.1 request ``harness``).
DEFAULT_HARNESS = "codex"


def main(argv: list[str] | None = None) -> int:
    """
    Dispatch a codex router-hook subcommand.

    :param argv: Argv override excluding the program name. ``None`` reads
        :data:`sys.argv`.
    :returns: Process exit code. Always ``0`` — verdicts travel on stdout
        so a hook failure never wedges codex.
    """
    raw_argv = sys.argv[1:] if argv is None else argv
    command = raw_argv[0] if raw_argv else ""
    if command == "route-subagent":
        return _main_route_subagent(raw_argv[1:])
    if command == "session-canary":
        return _main_session_canary(raw_argv[1:])
    if command == "record-subagent":
        return _main_record_subagent(raw_argv[1:])
    print(f"omnigent codex router hook: unknown subcommand {command!r}", file=sys.stderr)
    return 0


def _parse_args(prog: str, argv: list[str], *, harness: bool = False) -> argparse.Namespace:
    """
    Parse one subcommand's arguments.

    :param prog: Program label for usage errors.
    :param argv: Argv after the subcommand.
    :param harness: Accept the routing-only ``--harness`` /
        ``--parent-model`` flags.
    :returns: Parsed namespace.
    """
    parser = argparse.ArgumentParser(prog=prog)
    parser.add_argument("--bridge-dir", required=True)
    parser.add_argument("--session-id", default=None)
    if harness:
        parser.add_argument("--harness", default=DEFAULT_HARNESS)
        parser.add_argument("--parent-model", default=None)
    return parser.parse_args(argv)


def _read_payload() -> dict[str, Any] | None:  # type: ignore[explicit-any]  # hook payloads are untrusted JSON
    """
    Read the hook payload from stdin.

    :returns: Decoded object, or ``None`` when stdin is empty or not a
        JSON object.
    """
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except ValueError as exc:
        print(f"omnigent codex router hook: malformed JSON: {exc}", file=sys.stderr)
        return None
    return payload if isinstance(payload, dict) else None


def is_spawn_agent_tool(tool_name: Any) -> bool:  # type: ignore[explicit-any]  # hook payloads are untrusted JSON
    """
    Report whether a hook payload names codex's subagent-spawn tool.

    :param tool_name: ``tool_name`` from the hook payload, e.g.
        ``"collaborationspawn_agent"``.
    :returns: ``True`` when the (flattened) name ends in
        ``spawn_agent``.
    """
    if not isinstance(tool_name, str):
        return False
    return tool_name.strip().lower().endswith(SPAWN_AGENT_TOOL_SUFFIX)


def build_route_request(
    tool_input: dict[str, Any],  # type: ignore[explicit-any]  # hook payloads are untrusted JSON
    *,
    harness: str,
    parent_model: str | None,
) -> dict[str, Any]:  # type: ignore[explicit-any]  # JSON request body
    """
    Build the ``route-subagent`` request body for a codex spawn.

    ``prompt`` is always ``null``: codex encrypts the spawn ``message``,
    so the task text is unavailable and the router sees ``task_name``
    plus session metadata only.

    :param tool_input: ``tool_input`` from the hook payload.
    :param harness: Requesting harness, e.g. ``"codex"``.
    :param parent_model: Model the parent session runs on, when known.
    :returns: JSON-serializable request body.
    """
    task_name = tool_input.get("task_name") or tool_input.get("agent_name")
    fork = tool_input.get("fork")
    return {
        "harness": harness,
        "task_name": task_name if isinstance(task_name, str) else "",
        "prompt": None,
        "fork": fork is True,
        "parent_model": parent_model,
    }


def _main_route_subagent(argv: list[str]) -> int:
    """
    Route one codex ``spawn_agent`` ``PreToolUse`` payload.

    Every failure path — non-spawn tool, missing advertisement,
    unreachable router, malformed response — emits nothing, which codex
    reads as "no opinion" and the spawn proceeds unchanged.

    :param argv: Argv after the ``route-subagent`` subcommand.
    :returns: Process exit code. Always ``0``.
    """
    args = _parse_args(
        "python -m omnigent.inner.hook_scripts.codex_router_hook route-subagent",
        argv,
        harness=True,
    )
    payload = _read_payload()
    if payload is None:
        return 0
    output = route_pre_tool_use(
        payload,
        router_dir=args.bridge_dir,
        session_id=args.session_id,
        harness=args.harness,
        parent_model=args.parent_model,
    )
    if output is not None:
        sys.stdout.write(json.dumps(output))
    return 0


def route_pre_tool_use(
    payload: dict[str, Any],  # type: ignore[explicit-any]  # hook payloads are untrusted JSON
    *,
    router_dir: str | Path,
    session_id: str | None = None,
    harness: str = DEFAULT_HARNESS,
    parent_model: str | None = None,
    timeout: float = REQUEST_TIMEOUT_S,
) -> dict[str, Any] | None:  # type: ignore[explicit-any]  # hook output JSON
    """
    Route one codex ``PreToolUse`` payload end to end.

    :param payload: Codex ``PreToolUse`` hook payload.
    :param router_dir: Bridge directory holding the router advertisement.
    :param session_id: Session baked into the hook command; the
        advertisement wins when it carries one.
    :param harness: Requesting harness, e.g. ``"codex-native"``.
    :param parent_model: Model the parent session runs on, when known.
    :param timeout: Socket timeout in seconds.
    :returns: Hook output, or ``None`` for "no opinion".
    """
    if not is_spawn_agent_tool(payload.get("tool_name")):
        return None
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return None
    endpoint = read_router_endpoint(router_dir)
    if endpoint is None:
        return None
    resolved = endpoint.session_id or session_id or resolve_session_id(endpoint)
    if not resolved:
        return None
    body = build_route_request(
        tool_input,
        harness=harness,
        parent_model=parent_model or _payload_model(payload),
    )
    decision = request_decision(endpoint, resolved, body, timeout=timeout)
    if decision is None:
        return None
    # The encrypted ``message`` rides along in *tool_input* untouched.
    return with_system_message(decision_to_hook_output(decision, tool_input))


def with_system_message(
    output: dict[str, Any] | None,  # type: ignore[explicit-any]  # hook output JSON
) -> dict[str, Any] | None:  # type: ignore[explicit-any]  # hook output JSON
    """
    Add the routed-model notice codex's TUI surfaces to the user.

    A rewrite is otherwise invisible: codex reports no model change of its
    own, so the top-level ``systemMessage`` (alongside, not inside,
    ``hookSpecificOutput``) is the only place the decision shows up. Same
    wording as ucode's codex routing (databricks/ucode PR 251).

    :param output: Hook output from :func:`decision_to_hook_output`, or
        ``None`` for "no opinion".
    :returns: *output* with a ``systemMessage`` when it rewrote the spawn's
        model, otherwise *output* unchanged.
    """
    if not isinstance(output, dict):
        return output
    hook_output = output.get("hookSpecificOutput")
    if not isinstance(hook_output, dict) or hook_output.get("permissionDecision") != "allow":
        return output
    updated_input = hook_output.get("updatedInput")
    if not isinstance(updated_input, dict):
        return output
    model = updated_input.get("model")
    if not isinstance(model, str) or not model:
        return output
    return {**output, "systemMessage": f"Using Intelligent Routing. Routing to {model}."}


def _payload_model(payload: dict[str, Any]) -> str | None:  # type: ignore[explicit-any]  # hook payloads are untrusted JSON
    """
    Extract the parent session's model from a hook payload.

    :param payload: Codex hook payload.
    :returns: Model id, or ``None`` when the payload carries none.
    """
    model = payload.get("model")
    return model if isinstance(model, str) and model else None


def canary_path(bridge_dir: str | Path) -> Path:
    """
    Path of the ``SessionStart`` canary file.

    :param bridge_dir: Session bridge directory.
    :returns: Canary file path.
    """
    return Path(bridge_dir) / CANARY_FILENAME


def audit_path(bridge_dir: str | Path) -> Path:
    """
    Path of the ``SubagentStart`` audit file.

    :param bridge_dir: Session bridge directory.
    :returns: Audit file path (JSON lines).
    """
    return Path(bridge_dir) / AUDIT_FILENAME


def _main_session_canary(argv: list[str]) -> int:
    """
    Touch the canary file proving the generated hooks ran.

    :param argv: Argv after the ``session-canary`` subcommand.
    :returns: Process exit code. Always ``0``.
    """
    args = _parse_args(
        "python -m omnigent.inner.hook_scripts.codex_router_hook session-canary", argv
    )
    path = canary_path(args.bridge_dir)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps({"session_id": args.session_id, "at": time.time()}),
            encoding="utf-8",
        )
    except OSError as exc:
        print(f"omnigent codex router hook: could not write canary: {exc}", file=sys.stderr)
    return 0


def _main_record_subagent(argv: list[str]) -> int:
    """
    Append one ``SubagentStart`` audit record.

    :param argv: Argv after the ``record-subagent`` subcommand.
    :returns: Process exit code. Always ``0``.
    """
    args = _parse_args(
        "python -m omnigent.inner.hook_scripts.codex_router_hook record-subagent", argv
    )
    payload = _read_payload()
    if payload is None:
        return 0
    record = {
        "agent_id": payload.get("agent_id") or payload.get("agentId"),
        "model": payload.get("model"),
        "task_name": payload.get("task_name"),
        "at": time.time(),
    }
    path = audit_path(args.bridge_dir)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(record) + "\n")
    except OSError as exc:
        print(f"omnigent codex router hook: could not write audit record: {exc}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
